/*
 * This source file was generated by the Gradle 'init' task
 */
package ApplicationTests;

import static org.junit.jupiter.api.Assertions.*;

import Application.controller.Controller;
import Application.model.Model;
import Application.view.View;
import org.junit.jupiter.api.Test;

public class AppTest {

    @Test
    public void testMain() {
            
            Model model = new Model();
            Controller controller = new Controller(model);
            View view = new View(controller);
    
            assertNotNull(view);
            assertNotNull(controller);
            assertNotNull(model);

          
    }
}

